### PR TITLE
#758 completed

### LINKED ISSUE #758: Scraper for a new website
Hi, would be great to have a scraper for TheExpertGuides.com
It already has recipe schema, but not picking up. 

Recipe link: https://theexpertguides.com/recipes/coconut-milk-pasta-sauce/

### PR DESCRIPTION
**Pull request by konandodev7**
Resolves #758 
I have added TheExpertGuides.com scraper.
I have tested it carefully and all is well.

### CODE REVIEW

**Comment by jayaddison** [comment]
@konandodev7 could you edit the description of this GitHub pull request to add the phrase `Resolves #758` at the end (or elsewhere within the message, if you prefer)?  That should allow GitHub to automatically close the linked bug #758 if+when this is merged (reviewing the code currently; it looks good to me so far).

**Review by jayaddison — APPROVED** [review]
Looks good to me!  Thanks again @konandodev7.  I'll plan to merge these changes within the next ~5-8 hours or so.

**Review by hhursev — APPROVED** [review]

**Comment by jayaddison** [comment]
Ah, I've made a bit of a mess of merging this:

  * I've locally merged this branch into my `main` and `v15` local `git` branches.
  * I've pushed the `v15` branch to @hhursev's repository on GitHub (this one) - so those commits are now 'public' and probably shouldn't be removed.
  * The `main` branch for this repository doesn't accept merge commits, so my push to `main` failed - so it _doesn't_ contain the changes.

Any thoughts either of you on how we should fix that up?

**Comment by konandodev7** [comment]
I think the fastest way is that I make a new pull request about the changes above. How do you think about that, @jayaddison ?

**Comment by jayaddison** [comment]
Sure, that sounds good @konandodev7 :+1:

**Comment by jayaddison** [comment]
You are welcome, and thank you for contributing.

**Pull request closed without merging**
