### PR TITLE
Standardize code to "Best Practices"

### LINKED ISSUE #187: Style preference, types, and formatting
Hello,

I realize that i've been adding a bunch of parsers lately and I realized that I could also help out with repo maintenance so that you don't have to just bump versions every two days.

Is there an official style or format that the project intends to keep? I typically like to have an [editorconfig](https://editorconfig.org/) in my repo and use [black](https://github.com/psf/black) for Python.

Additionally, is there interest for using mypy to do static type analysis?

Just trying to feel the waters!

Thanks for this amazing repo!

### PR DESCRIPTION
**Pull request by bfcarpio**
Implements the following:

- [x] `Black` formatting on pre-commit
- [x] `flake8` formatting on pre-commit
- [x] End of File fixes on pre-commit
- [x] Trim trailing whitespace on pre-commit
- [x] Entire repo black formatted
- [x] Small fixes to remove `flake8` errors
- [x] Adds everything necessary for devs to `requirements.txt`
  * Adding `black` and `flake8` to `requirements.txt` is unnecessary since `pre-commit` will clone the repos for itself. However, *devs* might want the tools for their own use eg. editor integration. Entries can be removed if no other version management scheme will be used.
- [x] `Black` badge
- [x] Update dev instructions for contributing
- [x] FAQ for how to determine if a website has schema
- [x] Add `Black` and `flake8` tasks to CI/CD.
  * This prevents "bad" merges if people use a web ui to edit files.

I'd like for others to try creating a new `venv` and seeing if all the pre-commit hooks work. Editor integration for `flake8` should be automatic if the editor supports it.

## IMPORTANT

+ Currently doesn't touch the CI/CD, but that can be quickly added. I've never used Travis, but I assume that I can just add in the line to run black and flake8 in the `script` section.
+ Requires Python 3.6+

closes #187

### CODE REVIEW

**Comment by bfcarpio** [comment]
The failed check above is due to a Python 3.5 compatibility issue which is known.

**Comment by jayaddison** [comment]
@bfcarpio Could we upgrade the version of [coverage](https://github.com/hhursev/recipe-scrapers/blob/1030f3571be575d2d5b01fa559b0e304ba65fa59/requirements.txt#L2) to solve the Python 3.5 compatibility issue?

**Comment by bfcarpio** [comment]
@jayaddison `pre-commit` itself requires Python 3.6.1+.

In commit 2ea6835 I removed the 3.5 runner in Travis and updated `setup.py`.

**Comment by jayaddison** [comment]
@bfcarpio Ah, cool - that makes sense :)  Thanks for the explanation!

**Comment by hhursev** [comment]
It's awesome 😍  Feel free to merge. 👍 👍  I didn't expect to see flake8 and it's a nice touch too.

Can you also edit README.rst and add `pre-commit install &&` after the pip install line in the "For Devs" section. Hah, adding the Black project badge will be a nice touch too.

Good stuff!

**Comment by bfcarpio** [comment]
@hhursev I was hoping to get more guidance from you about package management. I started bringing it up in #178 

IMO, python has one of the worst package management systems since there's no really nice way of specifying *development* and *production* dependencies. 

Currently, all dependencies would be be downloaded for production deployment and when imported by another project. We don't have too many things being pulled in redundantly, but it wastes bandwidth and space for others.

If we used something like [`pipenv`](https://pipenv.pypa.io/en/latest/) we could differentiate dependencies based on their use. Additionally, using a tool like `pipenv` would reduce some of the mental bandwidth since it follows conventions and has documentation etc.

If you're interested, I'd like to fit it into this PR, but it's up to you.

Regardless, once I know your opinion, I'll have to finish a couple of things (yes, even the badge :P) and then I'll merge.

**Comment by bfcarpio** [comment]
Alright, I updated the README based on your feedback and updated the CI/CD tasks.

@hhursev Since this is a huge PR, I'll leave the final button push to you. Could you do a once over on the CI/CD, dependencies, and packaging stuff?

**Comment by hhursev** [comment]
Everything looks awesome to me! Merging

**Pull request merged**
