### PR TITLE
Add scraper for lekkerensimpel.com

### PR DESCRIPTION
**Pull request by danielpalstra**
This PR adds a scraper for dutch recipe site https://lekkerensimpel.com

### CODE REVIEW

**Review by jayaddison — APPROVED** [review]
This looks great, thank you @danielpalstra!

An optional request: could you consider adding test coverage on the natural language detection for the scraper?

Example: https://github.com/hhursev/recipe-scrapers/blob/bb20d6e338af27de17eba00ade47ed51aa3b7d31/tests/test_woolworths.py#L75-L76

**Comment by danielpalstra** [comment]
@jayaddison I added the language method as requested.

**Comment by jayaddison** [comment]
Thanks again @danielpalstra - this is now available as part of `recipe-scrapers` v13.20.0, as [published on PyPi](https://pypi.org/project/recipe-scrapers/).

**Comment by danielpalstra** [comment]
> Thanks again @danielpalstra - this is now available as part of `recipe-scrapers` v13.20.0, as [published on PyPi](https://pypi.org/project/recipe-scrapers/).

Awesome, thanks!

**Pull request merged**
