### PR TITLE
Add scraper for NIH Healthy Eating website.

### PR DESCRIPTION
**Pull request by micahcochran**
This is for the website https://healthyeating.nhlbi.nih.gov

I'm a little unclear about the actual title of the website.  It is hosted by the U.S. National Institute of Health's (NIH) National Heart, Lung and Blood Institute (NHLBI).  I've chosen "Healthy Eating" as its name, but I've also seen "Delicious Healthy Heart Recipes" and "Keep the Beat™ Heart Healthy Recipes".  Also, this website seems to be [composed of a few cookbooks](https://healthyeating.nhlbi.nih.gov/about.aspx).  Whatever the actual name, the scraper library doesn't really care, but it is nice to have good names for whomever is maintaining the code.

So, I went with what I thought was a simplest title "NIH Healthy Eating".  I thought that these other names should be noted.  If the name needs to be changed, let me know.

Thank you.

### CODE REVIEW

**Comment by hhursev** [comment]
This site is awesome! I have never heard of it

Commenting on 2 topics - main and minor one.

Main (when this is done, I'll merge 🍺):

- Can you please add the site into the `README.md` file. Let’s name it `Healthy Eating` and link to the home page. Should be located right before the jamieoliver’s site.

Minor (you can skip this I don’t mind 💅):

- If I were to write the scraper, I’d omit the list slicing in the `ingredients` and `instructions` methods and make them look more alike the ones in the other classes.

For example:

```
ingredients_paragraphs = self.soup.find('div', {'id': "ingredients"}).findAll('p')

return [
    normalize_string(paragraph.get_text())
    for paragraph in ingredients_paragraphs
]
```

and

```
instructions_html = self.soup.find(
    'div', {'id': "recipe_directions"}).findAll('div', {'class': 'steptext’}
)

return '\n'.join([
    normalize_string(instruction.get_text())
    for instruction in instructions_html
])
```

or something like that. (I haven’t tested these but you get my idea).

**Comment by micahcochran** [comment]
Thanks for the great feedback.  The provided code worked with little/no modification.  I've made the all the requested changes. (Dealing with git was really the hardest part.)  I also changed the test case recipe because the one I was using was a little unusual.

**Comment by hhursev** [comment]
Thanks!

**Comment by micahcochran** [comment]
Thank you.

**Pull request merged**
