### PR TITLE
Fix re import in koket scraper

### PR DESCRIPTION
**Pull request by cydanil**
Hi,

This PR fixes an unfortunate import in the `koket.se` scraper, introduced [here](https://github.com/hhursev/recipe-scrapers/commit/8500fd8e0f8a982325a2dc56b226416b749c5f7e).  
This also breaks the latest release.  

I tested this change by running `pytest -vv tests/` first, seeing the keket test fail, doing the change, and seeing all tests pass.  
I also checked that this fix makes my application start again.

Thanks!
Cyril

### CODE REVIEW

**Comment by hhursev** [comment]
Ouch! Thanks. :beers:  Merging and bumping version asap

**Comment by cydanil** [comment]
Ah, I just discovered the [`regex`](https://pypi.org/project/regex/) package.  
Perhaps I should revert this change and include regex to the requirements?

**Comment by cydanil** [comment]
Cool, thanks!

**Comment by hhursev** [comment]
Nah I definitely want koket to work with the build in `re` package. The `regex` package seems to have been installed as dependency from the `black` package which is only used while developing and is not part of the lib. Thanks for the PR!

**Pull request merged**
