### PR TITLE
Added author method for getting a recipe's author

### PR DESCRIPTION
**Pull request by blmayer**
Great package!

 I just added this piece of information I find important.

### CODE REVIEW

**Comment by blmayer** [comment]
Finally! Hahaha

**Comment by jayaddison** [comment]
Nice @blmayer!  It might be worth adding a matching `author` method to the `AbstractScraper` class as well (here's an example for `title` method: https://github.com/hhursev/recipe-scrapers/blob/ef90d985d0b59a8a9bb3c4ee28f681ba04b138fa/recipe_scrapers/_abstract.py#L43-L44).

That way, users of `recipe-scrapers` can run `recipe = scrape_me(url)` for any URL, and then when they run `recipe.author()` they'll either get a value if the method is implemented (as for BBC Food as you've provided), or a `NotImplementedException` in cases where the scraper for the URL's website needs more work.

**Comment by jayaddison** [comment]
Looks great, thanks :)

@hhursev any additional thoughts before this could merge?

**Comment by blmayer** [comment]
Nothing else for now.

Nice, thanks!

**Comment by hhursev** [comment]
@blmayer thanks for the addition! Merging 🍺

**Pull request merged**
