### PR TITLE
Updated test file for FarmhouseDelivery

### PR DESCRIPTION
**Pull request by khushhalm**
Tests are failing for FarmhouseDelivery becausae RECIPE_SCRAPERS_SETTINGS was not provided and hence when run throwing error 
`requests.exceptions.MissingSchema: Invalid URL "<_io.TextIOWrapper name='tests/test_data/farmhousedelivery_1.testhtml' mode='r' encoding='utf-8'>": No schema supplied. Perhaps you meant http://<_io.TextIOWrapper name='tests/test_data/farmhousedelivery_1.testhtml' mode='r' encoding='utf-8'>?`

Solution:
Added 
`os.environ[
            "RECIPE_SCRAPERS_SETTINGS"
        ] = "tests.test_data.test_settings_module.test_settings"` in setUp function in test file.

### CODE REVIEW

**Comment by khushhalm** [comment]
Hey, @jayaddison while working on #383 I noticed that FarmhouseDelivery tests are broken, so this is a fix for that.

**Comment by jayaddison** [comment]
@khushhalm Awesome, thank you for finding this problem!

After checking this out locally, if it's ok with you, I'd like to suggest a slightly different approach to configuring the filename and setting the environment variable.

The environment variable [can also be configured by the base `ScraperTest` class here](https://github.com/hhursev/recipe-scrapers/blob/cdc9e33dd719a943e2f244b67f4ded5e3be0c9ba/tests/__init__.py#L12-L15).  So we could call `super().setUp()` to re-use that:

```python
    def setUp(self):
        super().setUp()
        ...
```

...and -- I just learned this today -- it looks like there is a [built-in way to override test filenames](https://github.com/hhursev/recipe-scrapers/blob/cdc9e33dd719a943e2f244b67f4ded5e3be0c9ba/tests/__init__.py#L17-L21) in the scraper tests.  So we could use that too and potentially get a fairly clean result:

```python
    # tests/test_farmhousedelivery_1.py

    @property
    def test_file_name(self):
        return "{}_1".format(self.scraper_class.__name__.lower())

    def setUp(self):
        super().setUp()
```

...and then after that, because the `setUp` method is not doing anything else, we could remove it entirely from the test suites:

```python
    # tests/test_farmhousedelivery_1.py

    @property
    def test_file_name(self):
        return "{}_1".format(self.scraper_class.__name__.lower())
```

What do you think?  Thanks again for investigating and helping with all this!

**Comment by khushhalm** [comment]
This is much cleaner, I think we should go ahead with the later one:  

    # tests/test_farmhousedelivery_1.py

    @property
    def test_file_name(self):
        return "{}_1".format(self.scraper_class.__name__.lower())

I'll update these files and update the commit head:
`#tests/test_farmhousedelivery_1.py`
`#tests/test_farmhousedelivery_2.py`

**Review by jayaddison — APPROVED** [review]
Looks perfect, thank you @khushhalm!

**Pull request merged**
