### PR TITLE
add support for several sites

### PR DESCRIPTION
**Pull request by wassupluke**
adds support for: 
- FitSlowCookerQueen.com
- HeatherChristo.com
- EatLiveRun.com

### CODE REVIEW

**Comment by jknndy** [comment]
Hi @wassupluke, thanks for the contribution! On first pass it looks like it's likely ready for merge. Just one request, could you please create an entry in the supported sites section of the Read Me file in the correct spot?

Once the entry is created I'll take one last look over & merge if ready!

Thanks & happy holidays

**Comment by wassupluke** [comment]
@jknndy added the entries to the ReadMe. Should be good to go. :)

**Review by jknndy — APPROVED** [review]

**Comment by jknndy** [comment]
@wassupluke, this all look good and I'll plan to merge into the code base this afternoon! 

Just one thing to note, generally once pull request has been reviewed and approved you should avoid adding anything (except fixes or corrections if needed) to the same request, this example being support for EatLiveRun. It'd be better to add any separate changes to a new pull request so that the code doesn't need to be re-reviewed before closing it out!

**Comment by wassupluke** [comment]
Sounds good. That's kind of what I figured after I realized my push to my main branch updated this pull request. This is honestly my first time contributing to a project so I'm still trying to get the hang of things (I'm a nurse who self-taught git so any education is appreciated:)

**Pull request merged**
