### PR TITLE
Add support for grouprecipes.com

### LINKED ISSUE #872: website request: grouprecipes.com
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- http://www.grouprecipes.com/145264/slow-cooker-chicken-biscuits.html
- http://www.grouprecipes.com/32356/goulash-i-grew-up-with.html

(note: I'm working on a scraper for this currently)

### PR DESCRIPTION
**Pull request by jayaddison**
Resolves #872.

### CODE REVIEW

**Comment by jayaddison** [comment]
@jknndy could I get your help with review/commentary for this pull request?  (something of a trade for previous code reviews - although I don't think I can keep up with your pace of development!)

**Comment by jknndy** [comment]
@jayaddison, all looks good to me, added one comment about a possible description adjustment.

I'm going to tackle adding some ingredient grouping support to some of the preexisting scrapers in place of adding new ones for the moment which should make for some easier reviews!

**Comment by jayaddison** [comment]
Thanks @jknndy - I think your comment about the `description` field went missing?  I don't see it here.

**Comment by jknndy** [comment]
> Thanks @jknndy - I think your comment about the `description` field went missing? I don't see it here.

The .stripped_strings at the end of this removes the additional information that pops up if you click "Read more" unfortunately when you remove it it appends "read more" & "see less" to the output string. There doesn't seem to be many recipes that this applies to but I think the additional info could be useful on the odd occasion it appears.

For example on this recipe it omits "Biscuit dough finishes this dish off for a filling meal all in one scoop."

    def description(self):
        container = self.soup.find("div", {"class": "details"})
        description_text = container.find("p").text
        description_text = description_text.replace("Read more", "").replace("See less", "")
        return normalize_string(description_text)

**Comment by jayaddison** [comment]
> > Thanks @jknndy - I think your comment about the `description` field went missing? I don't see it here.
> 
> The .stripped_strings at the end of this removes the additional information that pops up if you click "Read more" unfortunately when you remove it it appends "read more" & "see less" to the output string.

Gotcha, yep.  That's intentional in this case - I usually prefer a shorter `description` than a longer one given the choice, and it seems like the site does a good job of choosing the first few sentences (so the text always appears to end at a sentence / full-stop boundary, as far as I can tell).

**Comment by jayaddison** [comment]
(or, equivalently, that if the mis-shapen cupcake is provided to someone, then othe participants are able to see that that happened, and figure out a bit for themselves about what went on there; benign/voluntary/well-humoured/etc.  I guess some could argue that a little bit of mischief and pecking-order behaviour is normal in social gatherings.. I think if we have the opportunity to do better, either at a cupcake party, or in a technical standard, then doing so is worth considering)

**Comment by jayaddison** [comment]
I think I'll pause now because this is getting a bit rambly and potentially off-topic - but thank you for the opportunity to discuss this.

**Comment by jayaddison** [comment]
Argh, wrong thread :)

**Comment by jayaddison** [comment]
Re-opening..

**Pull request merged**
