### PR TITLE
Add scraper for afghankitchenrecipes.com

### PR DESCRIPTION
**Pull request by jayaddison**
This scraper would benefit from an implementation of #301 - the example recipe includes instructions and ingredients that relate to separate components of the resulting meal.

### CODE REVIEW

**Comment by gaurav19063** [comment]
@jayaddison How many files have you changed and add for adding new website. could you please provide a summary and is it working fine?

**Comment by jayaddison** [comment]
Hi @gaurav19063 - usually there are four files that we need to modify for each website:

- [add] Python scraper code for the website
- [add] A test HTML file
- [add] A Python unit test that reads the HTML file and runs the scraper -- this helps to check that the scraper is working correctly
- [modify] The [main `recipe-scrapers` Python module](https://github.com/hhursev/recipe-scrapers/blob/6573860d3deba19dc00a2016ea964aa7de42f187/recipe_scrapers/__init__.py) to add the scraper

Your comment made me realize that I'd accidentally added two HTML files here.  Thanks!

**Comment by jayaddison** [comment]
@gaurav19063 Also, one more detail: there is a utility script called [`generate.py`](thttps://github.com/hhursev/recipe-scrapers/blob/6573860d3deba19dc00a2016ea964aa7de42f187/recipe_scrapers/__init__.py) that can do a lot of the work of adding the new files and updating the main module for us.

**Comment by hhursev** [comment]
Adding the site in the README and squash merge / bump version 🤔 lgtm

**Pull request merged**
