### PR TITLE
Mobkitchen.co.uk is now mob.co.uk

### PR DESCRIPTION
**Pull request by willembasson**

### CODE REVIEW

**Comment by jknndy** [comment]
Hi @willembasson, 

Few things needed here before we can merge in, firstly could you sync your branch with the newest version of this library? It'll fix some of the conflicts and will make things neater for the merge in. Also..

- [ ] Update the README entry to reflect the new url
- [ ] Change the classname & file names (scraper, test file, test html) to just mob to reflect the change


Let me know if you have any questions!

**Comment by willembasson** [comment]
I have updated the readme, class name and test files. Think that is everything but let me know if there is anything else I missed. I have left the reference to "mobkitchen.co.uk" as it does still redirect at the moment

**Comment by jknndy** [comment]
Thanks, looks great! 

I'll leave this open for a day or so in-case anyone else has anything to add before it's merged in!

**Review by jayaddison — APPROVED** [review]
I've nothing further to add - it looks good to me too :+1:

**Pull request merged**
