### PR TITLE
New scraper for argiro.gr with tests and new equipment method

### PR DESCRIPTION
**Pull request by Fagogenis**
1. Added a new scraper for https://www.argiro.gr/
2. Added new equipment method to get the equipment needed for a recipe. It showed up in https://www.argiro.gr/ so I decided to add it as a new feature. I am not really sure if I added correctly though because I use some new libraries that the project didn't include.
3. Added 1 test for https://www.argiro.gr/

### CODE REVIEW

**Comment by hhursev** [comment]
Hey, I'd like to merge this but will need you to:

- Remove the selenium dependency. You can either remove the equipment method altogether or refactor it to use bs4 alone
- Add the new site in the README too

**Comment by Fagogenis** [comment]
I removed the equipment method and the selenium depency. Now the scraper must be ready.

**Comment by jknndy** [comment]
@Fagogenis, just pushed a small linting fix but otherwise looks good for merge! While this PR was in progress I added the ability to have equipment as a possible output (see #982)

Once this is merged in I'll open a new PR that adds the equipment coverage using the new method.

**Review by jayaddison — APPROVED** [review]
Looks good - thank you @Fagogenis!

**Pull request merged**
