### PR TITLE
NIHHealthyEating: Improvements

### PR DESCRIPTION
**Pull request by micahcochran**
This PR:

- adds image()
- changes the test to another test that has an image function
- reorganizes functions to return empty values when there is no content or invalid content  (my code is not as pithy as the current code)

This is the code that I had at the start of issue  #393.  At this point, this is intended for discussion of that issue.  I'm fine with restructuring it to raise `ElementNotFoundInHtml` or some other exception.

### CODE REVIEW

**Review by bfcarpio — DISMISSED** [review]
In any of your if-statements that check for something existing, I'd prefer an exception to be thrown instead of setting a default value.

Otherwise, your code is clear and easy to read.

**Comment by micahcochran** [comment]
@bfcarpio The code should now raise the `ElementNotFoundInHtml` exception in most cases.

This also adds `OptionalElementNotFoundInHtml` to _exceptions.py. This exception is used for images, since that content may or may not be present.  This gives the programmer the ability to handle that the image not being present differently.

**Comment by bfcarpio** [comment]
I'm a bit conflicted about the `OptionalElementNotFoundInHtml` exception. Throughout this project we don't specify which items are more optional than others. There's more of a focus on grabbing what exists. If a website doesn't have images on any of their recipes then we don't implement the scraper and throw something about no implementation. This, the distinction of optional is a bit odd to make here.

@hhursev Any thoughts?

**Comment by micahcochran** [comment]
> If a website doesn't have images on any of their recipes then we don't implement the scraper and throw something about no implementation. This, the distinction of optional is a bit odd to make here.

It is optional because some of the recipes on the website have an image and others do not.

[New example with an image ](https://healthyeating.nhlbi.nih.gov/recipedetail.aspx?cId=0&rId=188)
[Old example without an image](https://healthyeating.nhlbi.nih.gov/recipedetail.aspx?linkId=17&cId=10&rId=247)

How should I make that distinction when some recipes the website have an image and others do not?

**Comment by hhursev** [comment]
In the beginning this package used to silence exceptions by default and return "defaulting" values like empty string, empty list etc.

Since v13 we changed the behavior and exceptions are bubbled all the way up. In short your image method should raise the exception. Do not return empty string in your .image method.

If you want the `recipe-scrapers` to handle the exceptions and return empty string (as it used to do in the past) check this code:

```
from recipe_scraper import scrape_me

scraper = scrape_me("https://healthyeating.nhlbi.nih.gov/recipedetail.aspx?linkId=17&cId=10&rId=247")
scraper.image()  # this will explode by default

# However if you change the "settings module"
import os

# to the old behavior .. (before v13)
os.environ["RECIPE_SCRAPERS_SETTINGS"] = "recipe_scrapers.settings.v12_settings"

scraper.image()  # the package will silence the exception and return empty string for you w/o the need of adjusting the method
```

That v12_settings module was done for the purpose long-time package users (like you 🍻 ⭐ ) to be able to quickly switch to the old behavior. (If I understand correct this is what you aim for 🤔 )

Check [the v12_settings file setup](https://github.com/hhursev/recipe-scrapers/blob/master/recipe_scrapers/settings]/v12_settings.py). You can write settings files of your own too.


LMK if this clears things up. I'd like to merge the additions from the PR.

**Comment by micahcochran** [comment]
I don't have any legacy code the relies upon v12 operation.  I want this to code work more predictably.  I welcome using exceptions that tell you when something isn't parsing correctly.  I'll revert the last commit, so this is the version that adds an exception `OptionalElementNotFoundInHtml`.

I'll submit another PR that raises `ElementNotFoundInHtml` for image().

Whichever one you choose to merge, just squash it and close the other.

**Comment by bfcarpio** [comment]
@hhursev I pinged you because I wanted your opinion on the `OptionalElementNotFoundInHtml`. I think everything else in this PR is fine to go in, but wasn't sure if we'd want to denote between an item being optional vs "required".

**Comment by hhursev** [comment]
Merged #401 instead

**Pull request closed without merging**
