### PR TITLE
fixed hellofresh yields scraper

### PR DESCRIPTION
**Pull request by ammacdonald3**
This resolves an error with the **yields()** function on the Hello Fresh scraper, as documented in Issue #226

### CODE REVIEW

**Comment by bfcarpio** [comment]
Alright! Glad you were able to make the PR.

So as you can see this code isn't passing some tests that we have. That's probably because there's something different between the page that we use in the test and the page that you're trying to get the recipe.

It might be that they updated the website to a new format and we need to adjust the test, but it also might be that there's something incorrect about your new implementation.

Can you try finding the live page of the recipe we're using in the test and checking if your code works for it? There's several ways to do this and none of them are really faster or better than the others.

You can run tests locally so that you don't need to push and wait for the runner to complete with the following:
> python -m coverage run -m unittest tests.test_hellofresh.py

**Comment by ammacdonald3** [comment]
Thanks so much for the explanation; this is the approach that I assumed we would need to take. I ran the tests before submitting the PR, but because I think that the source page structure changed, the failure seemed expected. I'm unfortunately having trouble finding a live page with the exact same recipe as the one defined in the test. The closest I've found is:
https://www.hellofresh.co.uk/recipes/thai-style-pork-stir-fry-wk-49-5a01c742450cfa39e02c5642

Are you okay with me updating the test file with new test cases based on what I see in the front-end for this page (or any other HelloFresh page)?

**Comment by bfcarpio** [comment]
Cool!

I also found a different link that it similarly titled. I'm going to assume that if your implementation works with these two recipes then your assumption is valid. If you could try a couple more in REPL by hand then that would be good too.

Feel free to swap out the test reference if your manual tests work out.

Additionally, I can see HelloFresh has several top level domains (`.com`, `.co.uk`, .`.co.nz`). You might want to make a small change so that all these domains are supported. If you're interested you can make this change. Should only take about 2 lines and `BBCFood` will be a good reference.

LINK: https://www.hellofresh.co.nz/recipes/thai-style-pork-stir-fry-5ba1d63e30006c582b3f6bf5

**Comment by ammacdonald3** [comment]
Hey, sorry for the delay. I have pushed a new commit that contains the updated test case info, and everything for Hello Fresh appears to pass as expected. I had to add an additional `strip()` to account for scenarios where the source does not include a quantity of an ingredient (for example "Salted Peanuts" instead of "8 Jars of Salted Peanuts"). Additionally, I thought that the existing function already accounted for different top level domains (lines 10-11 of hellofresh.py), but please let me know if you're seeing otherwise.

**Comment by bfcarpio** [comment]
Wow, thank you! The changes look good. I hope this will fit your needs as well as been a good learning experience for you as well.

Regarding the different top level domains, I just wanted a small addition so that it supported `.co.nz` and `.co.uk`. I may have been remembering a state. You're all good!

**Review by bfcarpio — APPROVED** [review]

**Comment by bfcarpio** [comment]
For some reason the travis blurb that's normally there isn't showing up, but I checked and your build is failing. Here's the debug:

```
Traceback (most recent call last):

  File "/home/travis/build/hhursev/recipe-scrapers/tests/test_epicurious.py", line 56, in test_reviews

    self.harvester_class.reviews()[0]["review_text"],

IndexError: list index out of range
```

**Comment by ammacdonald3** [comment]
Okay, I don't think that I modified the test_epicurious.py or epicurious.py files as part of this PR, but I can try to do some more research on the cause of the error. Do you know if the Master build also fails for this issue, or does this error only occur with my new code?

**Comment by hhursev** [comment]
hmm weird why tests are failing for this PR.. I believe the job done is deserves a merge so I'm just going to merge it. If the tests blow up in the master branch we'll resolve it later 😉  Thanks for the contribution and your time 🍺!

**Comment by hhursev** [comment]
FYI the tests started failing in master and you definitely weren't the cause 😉 It was the new `beautifulsoup` version that was the "party pooper"

**Pull request merged**
