### PR TITLE
Adds SchemaScraperFactory

### PR DESCRIPTION
**Pull request by jksimoniii**
Wraps the `AbstractScrapper` into a factory, providing the basic implementation.

### Usage
```
SchemaScraperFactory.generate(url)
```

### CODE REVIEW

**Comment by hhursev** [comment]
I approve this 👍  It's a nice addition and may be used for implementing a "go wild" mode of the package! (Which I assume is partly (if not fully) your intention too!).

I feel like you are being polite and don't want to touch the original package too much thus you've put the `cuisine` and `site_name` method in the factory.

Feel free to add the `cuisine` method in the `SchemaOrg` class.
And the `site_name` method in the `AbstractScraper` one. I like what I see here 😉

After we merge this I'll instantly incorporate a "go wild" mode! It's been on my "todo" for quite some time

**Comment by jksimoniii** [comment]
+1 for anything called "go wild mode"!

I moved `site_name` and `cuisine` to their respective places. `site_name` is independent of schema, since I am pulling it from Open Graph tags. I've had relatively good success with these `og:` tags.

**Comment by bfcarpio** [comment]
Could you provide docs for usage? At least something in our small dev section of the README?

**Comment by jksimoniii** [comment]
@bfcarpio yes, of course! Updated https://github.com/hhursev/recipe-scrapers/pull/233/commits/fef06219a502880c1d7e30b0bb93f12f5e8eff42

**Review by bfcarpio — APPROVED** [review]
Thank you! Little things like this always makes this package approachable to people without a tech background!

**Comment by hhursev** [comment]
Thanks @jksimoniii 🍻🍻!  I will use your work as basis to implement some things that will bump us to version 10.x.x 😉

**Pull request merged**
