### PR TITLE
Add missing properties to Sally's Baking Addiction

### PR DESCRIPTION
**Pull request by krisnoble**
Adds the `cook_time`, `prep_time`, `description` and `cuisine` properties.

I'm a bit confused whether this scraper is necessary though since it doesn't override anything and wild mode seems to work fine? Looking at #617, is it more a case of "we know this works and can prove it with the tests"? Sorry if I'm missing something obvious, just trying to understand so I can better contribute :)

### CODE REVIEW

**Comment by jayaddison** [comment]
Hey @krisnoble - thanks for the pull request.  And yep, you've understood the structure - it's essentially a way to declare that we have some demonstrable level of basic support for a recipe website (from a certain point in time), and to iterate/repair that selectively - but surprisingly often `wild_mode=True` can indeed extract almost-or-all relevant recipe info as-is.

**Review by jayaddison — APPROVED** [review]
This looks good to me :+1:

**Comment by krisnoble** [comment]
Ah perfect thanks, glad I managed to get my head around it and happy to help!

**Comment by jayaddison** [comment]
@krisnoble this has been included and released in [`v14.56.0`](https://pypi.org/project/recipe-scrapers/14.56.0/) (and also the [pre-release `v15.0.0-rc3`](https://pypi.org/project/recipe-scrapers/15.0.0rc3/)) of `recipe-scrapers` on PyPi.

**Pull request merged**
