### PR TITLE
Addition: Support for https://www.madamecuisine.de

### PR DESCRIPTION
**Pull request by Gamekohl**
Doesn't resolve any issue but thought it would be useful to be implemented.

### CODE REVIEW

**Comment by Gamekohl** [comment]
@jayaddison sorry for pinging you. Do you have any idea why the unit tests keep failing? I've tried to figure it out but was not successful.
It keeps saying: "The host (madensverden.dk) doesn't match the expected host (madamecuisine.de)"
But I don't know why it expects the host madensverden.dk to be madamecuisine.de (which I have implemented)

**Comment by jknndy** [comment]
> It keeps saying: "The host (madensverden.dk) doesn't match the expected host (madamecuisine.de)"
> 
> But I don't know why it expects the host madensverden.dk to be madamecuisine.de (which I have implemented)

Once you add an readme entry (in alphabetical order) this should go away! I'll take a closer look in a bit but that should resolve it.

**Comment by jknndy** [comment]
> It keeps saying: "The host (madensverden.dk) doesn't match the expected host (madamecuisine.de)"
> 
> But I don't know why it expects the host madensverden.dk to be madamecuisine.de (which I have implemented)

Once you add an readme entry (in alphabetical order) this should go away! I'll take a closer look in a bit but that should resolve it.

**Comment by jayaddison** [comment]
@Gamekohl no problem - hopefully this is an easy fix :)

I think all that is required here is to add an entry for the website in the `README.rst` file - that's where the site is expected to be found.

It should be possible to confirm a fix locally, although note that you may need to run `pip install -e .` to reinstall the package's metadata.

**Comment by Gamekohl** [comment]
@jayaddison thank you, that did the trick

**Comment by jayaddison** [comment]
Almost perfect - thanks again @Gamekohl.  I think the only remaining change here is to make use of the `recipe_scrapers._utils.get_yields` utility function to wrap the return value from `def yields` -- for consistency with the interface/format we provide (it's not ideal -- that data can be a little unstructured/difficult-to-parse.. but consistency is nonetheless worthwhile until we can improve).

**Comment by jayaddison** [comment]
(and my apologies for taking a while to re-review)

**Comment by Gamekohl** [comment]
@jayaddison done!

**Review by jayaddison — APPROVED** [review]
Looks good to me - thanks again @Gamekohl!

**Pull request merged**
