### PR TITLE
Fixes #171

### LINKED ISSUE #171: Additional recipe sites
Hi -

Thank you for maintaining this recipe-scraper which I intend to incorporate in a current project.  Following are a couple of excellent and extensive recipe sites that I frequently use:

foodandwine.com - Sample recipe:
https://www.foodandwine.com/recipes/balsamic-and-rosemary-marinated-florentine-steak

amazingribs.com - Sample recipe:
https://amazingribs.com/tested-recipes/pork-recipes/perfect-pulled-pork-recipe

It would be wonderful if these sites were added to your functionality.

### LINKED ISSUE #208: I have a couple websites - I would love if someone could add them
I'm going to try to add them myself, but i'm not the most experienced programmer so I would appreciate if someone could help.
I checked these two websites and it appears they may not have schemas available after looking for 'application/ld+json' in inspect element.
If anything, I would prefer the first one. I'm using recipepuppy, and API for a project, and the top two recipe websites show up frequently.

https://cookeatshare.com/recipes/pork-steak-vegetable-bake-24221
http://www.grouprecipes.com/4766/brunswick-macaroni-soup.html
https://www.cooks.com/recipe/z25370wm/easy-onion-steak-potatoes.html
https://www.cdkitchen.com/recipes/recs/473/Veal-Steak-Vesuvio92364.shtml

Thanks a lot

### PR DESCRIPTION
**Pull request by bluhmr**
We have implemented scrapers for AmazingRibs.com and FoodAndWine.com, fixing #171 .  We have also partially fixed #208 by adding CookEatShare and CDKitchen scrapers.  We intend to add group recipes and cooks this weekend!

### CODE REVIEW

**Comment by bluhmr** [comment]
My partner @sloanemk and I have, in our most recent push to my fork, added support for nutrients which was requested in Issue #241

**Comment by hhursev** [comment]
What I see here is great job. 👏 🐝 🍻  Thanks!

Merging and bumping version.

Any reason you've decided .nutrients to return list 🤔 I think dict is more appropriate in this case

**Comment by bluhmr** [comment]
We had implemented it as a dictionary initially but we  were pretty conflicted about it and decided to go with a list so it was the same as the ingredients list,  I can change it back for sure!

**Comment by bluhmr** [comment]
I just submit another request to have nutrients return a list, I agree with you, I think that works better!

**Pull request merged**
