### PR TITLE
Adds MobKitchen Scraper (#506)

### PR DESCRIPTION
**Pull request by conor-f**

### CODE REVIEW

**Comment by jayaddison** [comment]
This looks good to me, thanks @conor-f! (and thanks for spotting and fixing up the unit test instructions at the same time)

Some small formatting issues to fix up and then this should be ready to merge :+1:

**Comment by conor-f** [comment]
Think that should do it. There was an issue that'd have to be fixed in a few days anyways RE: Black and Click discussed [here](https://github.com/psf/black/issues/2964).

**Review by jayaddison — APPROVED** [review]

**Comment by jayaddison** [comment]
Merged and release in [v13.26.0](https://github.com/hhursev/recipe-scrapers/releases/tag/13.26.0) of the library (also available on PyPi).

**Comment by hhursev** [comment]
very nice PR ! ⭐

**Pull request merged**
