### PR TITLE
added eattolerant.de

### PR DESCRIPTION
**Pull request by jlssmt**
Hello @jayaddison can you look over it please? I'm new to this repo.

### CODE REVIEW

**Review by jayaddison — APPROVED** [review]
Looks good to me @jlssmt - I can't see any problems with the code, and will start the continuous integration tests.

If you want to, one additional step to make the changes more robust could be to match all of the scraper methods (`title`, `description`, ...) with a corresponding test method.  At the moment I think a few methods only exist in the scraper and not the test, or vice-versa.

**Review by jayaddison — CHANGES_REQUESTED** [review]
Ah, one problem that I didn't notice... :)

The test HTML is missing from your branch - we'll need that in place so that the unit tests can pass during continuous integration.

**Comment by jayaddison** [comment]
(note: some tests fail locally when I run this locally; there may be duplicate newlines in the `test_instructions` assert expectation?)

**Comment by jayaddison** [comment]
Hey @jlssmt - apologies for taking a while to look at this again.  Could you investigate the unit test failures?  My guess is that there is a mismatch between the test HTML data and the test expectations (hopefully a straightforward fix).

**Comment by jlssmt** [comment]
@jayaddison 
unit tests are fixed now.
i don't know how to fix lint. `tox -e lint` is not working on my machine.

**Comment by jayaddison** [comment]
Thanks @jlssmt - what's the error you see when you run `tox`?

**Comment by jlssmt** [comment]
@jayaddison 
image

**Comment by jayaddison** [comment]
@jlssmt could you try merging the latest changes from the `main` branch into yours?

In particular, the most recent commit there (to update `pre-commit`) should fix those errors, I think.

**Comment by jlssmt** [comment]
@jayaddison 
thanks. lint should be fixed also now.

**Comment by jayaddison** [comment]
Perfect!  Thanks @jlssmt - merging.  This scraper should be available in a published version of `recipe-scrapers` soon.

**Review by jayaddison — APPROVED** [review]

**Comment by jayaddison** [comment]
This is now available in `recipe-scrapers` v14.30.0 :tada:

**Comment by jlssmt** [comment]
@jayaddison 
thanks. so just mealie needs an update ;-)

**Pull request merged**
