### PR TITLE
Handle case where ingredients are in subheaders

### PR DESCRIPTION
**Pull request by ptoczko**
Fixes https://github.com/hhursev/recipe-scrapers/issues/595

### CODE REVIEW

**Review by jayaddison — APPROVED** [review]
Thanks @ptoczko!

Local review: looks good, the fix works as [expected](https://github.com/hhursev/recipe-scrapers/issues/595#issue-1362096518) :+1: 

```
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me('https://www.greatbritishchefs.com/recipes/beef-mushroom-lasagne-recipe')
>>> print(scraper.ingredients())
['1 lasagne pasta, packet', '50g of Parmesan', 'oil', '2 onions, finely chopped', '700g of beef mince', '6 bacon rashers, diced', '3 tin of chopped tomatoes', '1 bay leaf', '250ml of red wine', '', '70g of butter', '50g of plain flour', '500ml of milk', '200g of chestnut mushrooms, sliced', '100g of button mushrooms, sliced', '100g of girolles, sliced', '1 handful of porcini mushroom', '6 sage leaves']
```

...plus no regressions discovered in the existing test coverage or the additional example provided in the issue.

An optional extra / nice-to-have: an additional scraper test for multi-heading ingredient lists on this website?

(and one small lint error to cleanup before merge)

**Comment by ptoczko** [comment]
Hey @jayaddison quick question i'm having trouble with precommit hooks was wondering if you've seen this before
```
    × Encountered error while trying to install package.
    ╰─> ruamel.yaml.clib
```

**Comment by jayaddison** [comment]
> Hey @jayaddison quick question i'm having trouble with precommit hooks was wondering if you've seen this before
> 
> ```
>     × Encountered error while trying to install package.
>     ╰─> ruamel.yaml.clib
> ```

Hey - can't say I have; that's weird.  My guess is that this could be from a global commit hook, because `recipe-scrapers` doesn't add any of its' own.

Wild guess: perhaps a failure to find a pre-built wheel for your development OS/environment ( https://pypi.org/project/ruamel.yaml.clib/#files shows pre-built options available), followed by a failure to compile the package from scratch?  If so, attempting to install the same package name into a local virtualenv might display the problem.

**Comment by ptoczko** [comment]
I think ive fixed the lint errors now

**Comment by jayaddison** [comment]
Nice work @ptoczko - thanks for adding the test coverage.  lgtm :+1:

**Comment by jayaddison** [comment]
Fix released to PyPi in `recipe-scrapers` v14.14.0 - thanks again!

**Pull request merged**
