### PR TITLE
fixed #742

### LINKED ISSUE #742: suggestion for adding a site
noticed nibbledish.com was not working and didn't see a reason why it wouldn't

http://nibbledish.com/soon-dubu-chigae/ 

is an example

### PR DESCRIPTION
**Pull request by konandodev7**

### CODE REVIEW

**Comment by konandodev7** [comment]
In the nibbledish.com, the variable **recipeIngredient** is **str** type.
Ex: "recipeIngredient": "3 tablespoons of red pepper powder..."
So the output of the ingredients was the array of single character.
Ex: ['3', '', 't', 'a', 'b', 'l', 'e', 's', 'p', 'o', ...]
To solve this problem, I added below code in /recipe_scrapers/_schemaorg.py.
        if ingredients and isinstance(ingredients, str):
            ingredients = [ingredients]

**Comment by jayaddison** [comment]
Thanks, @konandodev7!  This looks like a good improvement.  Could you add some test coverage (a test HTML file, and a Python test file under the `tests` directory) that demonstrates the fixed results?

**Comment by konandodev7** [comment]
Thanks for your comments, @jayaddison.
I have added nibbledish scraper and test HTML file, and a Python test file.
I have tested it and the test result is perfect.

**Comment by hhursev** [comment]
Hey hey, thanks! Everything looks good!

Can you please just add the site in the README too and we'll merge and bump version for you.

**Comment by konandodev7** [comment]
Thanks. @hhursev.
I have added the site in the README and committed it.
I think all is well.
I am looking forward to your next advice. Thanks.

**Comment by jayaddison** [comment]
Nice work, thank you @konandodev7!

**Pull request merged**
