### PR TITLE
Add scraper for godt.no

### PR DESCRIPTION
**Pull request by lurimax-north**
Adds a scraper for the recipe site godt.no

used https://www.godt.no/oppskrifter/pannekaker-og-vafler/8749/grove-middagspannekaker for the test html file.

### CODE REVIEW

**Comment by jayaddison** [comment]
Hey @lurimax-north - thanks for the scraper!  It looks good to me; could you look into the lint failures and fix those up (one module import ordering issue, and one `black` formatting issue in a test by the looks of it).

**Comment by jvlomax-hbb** [comment]
> Hey @lurimax-north - thanks for the scraper! It looks good to me; could you look into the lint failures and fix those up (one module import ordering issue, and one `black` formatting issue in a test by the looks of it).

Thanks. Been meaning to look into it. The python install on my laptop has gone haywire, just need to fix it so I can actually run the linters. Will have it fixed in a day or two

**Comment by lurimax-north** [comment]
@jayaddison Sorry for the delay, all linted

**Review by jayaddison — APPROVED** [review]
Looks good to me; thanks @lurimax-north!

**Comment by jayaddison** [comment]
This is now available in version [`14.33.0` of `recipe-scrapers` on PyPi](https://pypi.org/project/recipe-scrapers/14.33.0/).

**Pull request merged**
